"""add seed_materials table

Revision ID: 08af157c9279
Revises: a1b2c3d4e5f6
Create Date: 2026-03-29 23:29:32.723257

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08af157c9279'
down_revision: Union[str, None] = 'a1b2c3d4e5f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seed_materials',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False),
    sa.Column('status', sa.String(length=20), server_default='generating', nullable=False),
    sa.Column('market_context', sa.JSON(), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=True),
    sa.Column('consumer_personas', sa.JSON(), nullable=True),
    sa.Column('discussion_topics', sa.JSON(), nullable=True),
    sa.Column('raw_response', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('generating', 'completed', 'failed')", name='ck_seed_material_status'),
    sa.ForeignKeyConstraint(['scenario_id'], ['simulation_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_seed_material_scenario_id', 'seed_materials', ['scenario_id'], unique=False, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_seed_material_scenario_id', table_name='seed_materials', postgresql_where='deleted_at IS NULL')
    op.drop_table('seed_materials')
    # ### end Alembic commands ###
