"""initial_schema

Revision ID: e0be03dab794
Revises: 
Create Date: 2026-03-28 21:23:02.949768

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e0be03dab794'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_templates',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('model_tier', sa.String(length=20), server_default='community', nullable=False),
    sa.Column('typical_count_min', sa.Integer(), nullable=True),
    sa.Column('typical_count_max', sa.Integer(), nullable=True),
    sa.Column('default_config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("model_tier IN ('core', 'community', 'edge')", name='ck_agent_template_model_tier'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index('ix_agent_template_role', 'agent_templates', ['role'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('projects',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('product_type', sa.String(length=50), nullable=True),
    sa.Column('target_market', sa.String(length=200), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('pricing_model', sa.String(length=100), nullable=True),
    sa.Column('competitors', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('active', 'archived')", name='ck_project_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_project_status', 'projects', ['status'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('simulation_scenarios',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('agent_count', sa.Integer(), server_default='100', nullable=False),
    sa.Column('agent_depth', sa.String(length=20), server_default='standard', nullable=False),
    sa.Column('market_config', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("agent_depth IN ('quick', 'standard', 'deep')", name='ck_scenario_agent_depth'),
    sa.CheckConstraint('agent_count > 0', name='ck_scenario_agent_count_positive'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_scenario_project_id', 'simulation_scenarios', ['project_id'], unique=False, postgresql_where='deleted_at IS NULL')
    op.create_table('simulation_runs',
    sa.Column('scenario_id', sa.Uuid(), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('result_summary', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending', 'running', 'completed', 'failed')", name='ck_run_status'),
    sa.ForeignKeyConstraint(['scenario_id'], ['simulation_scenarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_run_scenario_id', 'simulation_runs', ['scenario_id'], unique=False, postgresql_where='deleted_at IS NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_run_scenario_id', table_name='simulation_runs', postgresql_where='deleted_at IS NULL')
    op.drop_table('simulation_runs')
    op.drop_index('ix_scenario_project_id', table_name='simulation_scenarios', postgresql_where='deleted_at IS NULL')
    op.drop_table('simulation_scenarios')
    op.drop_index('ix_project_status', table_name='projects', postgresql_where='deleted_at IS NULL')
    op.drop_table('projects')
    op.drop_index('ix_agent_template_role', table_name='agent_templates', postgresql_where='deleted_at IS NULL')
    op.drop_table('agent_templates')
    # ### end Alembic commands ###
