/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_api_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Projects */
        get: operations["list_projects_api_projects_get"];
        put?: never;
        /** Create Project */
        post: operations["create_project_api_projects_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Project */
        get: operations["get_project_api_projects__project_id__get"];
        put?: never;
        post?: never;
        /** Delete Project */
        delete: operations["delete_project_api_projects__project_id__delete"];
        options?: never;
        head?: never;
        /** Update Project */
        patch: operations["update_project_api_projects__project_id__patch"];
        trace?: never;
    };
    "/api/projects/{project_id}/ai-complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ai Complete Project */
        post: operations["ai_complete_project_api_projects__project_id__ai_complete_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/projects/{project_id}/scenarios": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Scenarios */
        get: operations["list_scenarios_api_projects__project_id__scenarios_get"];
        put?: never;
        /** Create Scenario */
        post: operations["create_scenario_api_projects__project_id__scenarios_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/scenarios/{scenario_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Scenario */
        get: operations["get_scenario_api_scenarios__scenario_id__get"];
        put?: never;
        post?: never;
        /** Delete Scenario */
        delete: operations["delete_scenario_api_scenarios__scenario_id__delete"];
        options?: never;
        head?: never;
        /** Update Scenario */
        patch: operations["update_scenario_api_scenarios__scenario_id__patch"];
        trace?: never;
    };
    "/api/scenarios/{scenario_id}/runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Runs */
        get: operations["list_runs_api_scenarios__scenario_id__runs_get"];
        put?: never;
        /** Create Run */
        post: operations["create_run_api_scenarios__scenario_id__runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/runs/{run_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Run */
        get: operations["get_run_api_runs__run_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Run Status */
        patch: operations["update_run_status_api_runs__run_id__patch"];
        trace?: never;
    };
    "/api/agent-templates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Agent Templates */
        get: operations["list_agent_templates_api_agent_templates_get"];
        put?: never;
        /** Create Agent Template */
        post: operations["create_agent_template_api_agent_templates_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/agent-templates/{template_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Agent Template */
        get: operations["get_agent_template_api_agent_templates__template_id__get"];
        put?: never;
        post?: never;
        /** Delete Agent Template */
        delete: operations["delete_agent_template_api_agent_templates__template_id__delete"];
        options?: never;
        head?: never;
        /** Update Agent Template */
        patch: operations["update_agent_template_api_agent_templates__template_id__patch"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AgentTemplateCreate */
        AgentTemplateCreate: {
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Description */
            description?: string | null;
            /**
             * Modeltier
             * @default community
             * @enum {string}
             */
            modelTier: "core" | "community" | "edge";
            /** Typicalcountmin */
            typicalCountMin?: number | null;
            /** Typicalcountmax */
            typicalCountMax?: number | null;
            /** Defaultconfig */
            defaultConfig?: {
                [key: string]: unknown;
            };
        };
        /** AgentTemplateRead */
        AgentTemplateRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Name */
            name: string;
            /** Role */
            role: string;
            /** Description */
            description: string | null;
            /** Modeltier */
            modelTier: string;
            /** Typicalcountmin */
            typicalCountMin: number | null;
            /** Typicalcountmax */
            typicalCountMax: number | null;
            /** Defaultconfig */
            defaultConfig: {
                [key: string]: unknown;
            };
        };
        /** AgentTemplateUpdate */
        AgentTemplateUpdate: {
            /** Name */
            name?: string | null;
            /** Role */
            role?: string | null;
            /** Description */
            description?: string | null;
            /** Modeltier */
            modelTier?: ("core" | "community" | "edge") | null;
            /** Typicalcountmin */
            typicalCountMin?: number | null;
            /** Typicalcountmax */
            typicalCountMax?: number | null;
            /** Defaultconfig */
            defaultConfig?: {
                [key: string]: unknown;
            } | null;
        };
        /** AICompleteCompletions */
        AICompleteCompletions: {
            /** Description */
            description?: string | null;
            /** Targetmarket */
            targetMarket?: string | null;
            /** Targetaudience */
            targetAudience?: string | null;
            /** Pricingmodel */
            pricingModel?: string | null;
            /** Competitors */
            competitors?: string[] | null;
        };
        /** AICompleteMetadata */
        AICompleteMetadata: {
            /** Model */
            model: string;
            /** Fieldscompleted */
            fieldsCompleted: string[];
            /** Fieldsskipped */
            fieldsSkipped: string[];
        };
        /** AICompleteResponse */
        AICompleteResponse: {
            completions: components["schemas"]["AICompleteCompletions"];
            metadata: components["schemas"]["AICompleteMetadata"];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** HealthResponse */
        HealthResponse: {
            /** Status */
            status: string;
            /** Version */
            version: string;
            /** Database */
            database: string;
        };
        /** PaginatedResponse[AgentTemplateRead] */
        PaginatedResponse_AgentTemplateRead_: {
            /** Items */
            items: components["schemas"]["AgentTemplateRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
        };
        /** PaginatedResponse[ProjectRead] */
        PaginatedResponse_ProjectRead_: {
            /** Items */
            items: components["schemas"]["ProjectRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
        };
        /** PaginatedResponse[RunRead] */
        PaginatedResponse_RunRead_: {
            /** Items */
            items: components["schemas"]["RunRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
        };
        /** PaginatedResponse[ScenarioRead] */
        PaginatedResponse_ScenarioRead_: {
            /** Items */
            items: components["schemas"]["ScenarioRead"][];
            /** Total */
            total: number;
            /** Page */
            page: number;
            /** Pagesize */
            pageSize: number;
        };
        /** ProjectCreate */
        ProjectCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /** Producttype */
            productType?: string | null;
            /** Targetmarket */
            targetMarket?: string | null;
            /** Targetaudience */
            targetAudience?: string | null;
            /** Pricingmodel */
            pricingModel?: string | null;
            /** Competitors */
            competitors?: string[];
            /** Status */
            status?: ("draft" | "active") | null;
        };
        /** ProjectRead */
        ProjectRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Producttype */
            productType: string | null;
            /** Targetmarket */
            targetMarket: string | null;
            /** Targetaudience */
            targetAudience: string | null;
            /** Pricingmodel */
            pricingModel: string | null;
            /** Competitors */
            competitors: string[];
            /** Status */
            status: string;
        };
        /** ProjectUpdate */
        ProjectUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Producttype */
            productType?: string | null;
            /** Targetmarket */
            targetMarket?: string | null;
            /** Targetaudience */
            targetAudience?: string | null;
            /** Pricingmodel */
            pricingModel?: string | null;
            /** Competitors */
            competitors?: string[] | null;
            /** Status */
            status?: ("draft" | "active" | "archived") | null;
        };
        /** RunCreate */
        RunCreate: Record<string, never>;
        /** RunRead */
        RunRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /**
             * Scenarioid
             * Format: uuid
             */
            scenarioId: string;
            /** Status */
            status: string;
            /** Startedat */
            startedAt: string | null;
            /** Completedat */
            completedAt: string | null;
            /** Resultsummary */
            resultSummary: {
                [key: string]: unknown;
            } | null;
        };
        /** RunStatusUpdate */
        RunStatusUpdate: {
            /**
             * Status
             * @enum {string}
             */
            status: "running" | "completed" | "failed";
            /** Startedat */
            startedAt?: string | null;
            /** Completedat */
            completedAt?: string | null;
            /** Resultsummary */
            resultSummary?: {
                [key: string]: unknown;
            } | null;
        };
        /** ScenarioCreate */
        ScenarioCreate: {
            /** Name */
            name: string;
            /** Description */
            description?: string | null;
            /**
             * Agentcount
             * @default 100
             */
            agentCount: number;
            /**
             * Agentdepth
             * @default standard
             * @enum {string}
             */
            agentDepth: "quick" | "standard" | "deep";
            /** Marketconfig */
            marketConfig?: {
                [key: string]: unknown;
            };
        };
        /** ScenarioRead */
        ScenarioRead: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
            /**
             * Projectid
             * Format: uuid
             */
            projectId: string;
            /** Name */
            name: string;
            /** Description */
            description: string | null;
            /** Agentcount */
            agentCount: number;
            /** Agentdepth */
            agentDepth: string;
            /** Marketconfig */
            marketConfig: {
                [key: string]: unknown;
            };
        };
        /** ScenarioUpdate */
        ScenarioUpdate: {
            /** Name */
            name?: string | null;
            /** Description */
            description?: string | null;
            /** Agentcount */
            agentCount?: number | null;
            /** Agentdepth */
            agentDepth?: ("quick" | "standard" | "deep") | null;
            /** Marketconfig */
            marketConfig?: {
                [key: string]: unknown;
            } | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_check_api_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    list_projects_api_projects_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ProjectRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_project_api_projects_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_project_api_projects__project_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_project_api_projects__project_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_project_api_projects__project_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProjectRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_scenarios_api_projects__project_id__scenarios_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_ScenarioRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_scenario_api_projects__project_id__scenarios_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_scenario_api_scenarios__scenario_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_scenario_api_scenarios__scenario_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_scenario_api_scenarios__scenario_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ScenarioUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ScenarioRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_runs_api_scenarios__scenario_id__runs_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
            };
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_RunRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_run_api_scenarios__scenario_id__runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                scenario_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_run_api_runs__run_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_run_status_api_runs__run_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                run_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RunStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RunRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    ai_complete_project_api_projects__project_id__ai_complete_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                project_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AICompleteResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_agent_templates_api_agent_templates_get: {
        parameters: {
            query?: {
                page?: number;
                pageSize?: number;
                role?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PaginatedResponse_AgentTemplateRead_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_agent_template_api_agent_templates_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentTemplateCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_agent_template_api_agent_templates__template_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    delete_agent_template_api_agent_templates__template_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_agent_template_api_agent_templates__template_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                template_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AgentTemplateUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentTemplateRead"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}

// ─── Convenience aliases (matched to backend schemas) ────────────────────────
export type ProjectRead = components["schemas"]["ProjectRead"];
export type ProjectCreate = components["schemas"]["ProjectCreate"];
export type ProjectUpdate = components["schemas"]["ProjectUpdate"];
export type AgentTemplateRead = components["schemas"]["AgentTemplateRead"];
export type PaginatedProjects = components["schemas"]["PaginatedResponse_ProjectRead_"];
export type PaginatedAgentTemplates = components["schemas"]["PaginatedResponse_AgentTemplateRead_"];
export type AICompleteResponse = components["schemas"]["AICompleteResponse"];
export type AICompleteCompletions = components["schemas"]["AICompleteCompletions"];
export type AICompleteMetadata = components["schemas"]["AICompleteMetadata"];

// Pages not yet connected to real API use these local types until their phase.
// Remove each when the corresponding page gets real data.
export interface OverviewStats {
  activeProjects: number;
  ideasInPipeline: number;
  runningSimulations: number;
  completedReports: number;
  avgValidationScore: number;
}

export interface ActivityLog {
  id: string;
  action_type: string;
  entity_type: string | null;
  created_at: string;
}

export interface SimulationScenario {
  id: string;
  project_id: string;
  name: string;
  description: string | null;
  created_at: string;
}

export interface SimulationRun {
  id: string;
  scenarioId: string;
  status: string;
  startedAt: string | null;
  completedAt: string | null;
  resultSummary: Record<string, unknown> | null;
  createdAt: string;
}

export interface MarketValidationResult {
  id: string;
  simulation_run_id: string;
  adoption_score: number | null;
  willingness_to_pay_score: number | null;
  retention_score: number | null;
  objection_score: number | null;
  sentiment_score: number | null;
  conversion_rate: number | null;
  churn_risk: number | null;
  summary: string | null;
  created_at: string;
}

export interface BusinessViabilityResult {
  id: string;
  simulation_run_id: string;
  projected_revenue: number | null;
  projected_cost: number | null;
  projected_profit: number | null;
  break_even_month: number | null;
  market_share_estimate: number | null;
  survival_probability: number | null;
  unit_economics: Record<string, number>;
  summary: string | null;
  created_at: string;
}

export interface Report {
  id: string;
  project_id: string;
  simulation_run_id: string | null;
  title: string;
  executive_summary: string | null;
  report_status: "draft" | "generated" | "published";
  created_at: string;
}

export interface AdminUser {
  id: string;
  full_name: string;
  email: string;
  role: string;
  organisation: string | null;
  title: string | null;
  is_active: boolean;
  created_at: string;
}

export interface SimulationEvent {
  id: string;
  round: number;
  timestamp: string;
  agent_name: string;
  agent_type: AgentTemplateRead["role"];
  action: string;
  message: string;
  sentiment: "positive" | "neutral" | "negative";
  target_agent?: string;
}

export interface SimulationLiveState {
  run_id: string;
  scenario_name: string;
  status: "running" | "completed";
  current_round: number;
  total_rounds: number;
  start_time: string;
  metrics: {
    adoption_rate: number;
    market_sentiment: number;
    avg_willingness_to_pay: number;
    total_interactions: number;
    positive_ratio: number;
    negative_ratio: number;
  };
  agent_counts: Record<string, number>;
  events: SimulationEvent[];
  round_metrics: { round: number; adoption: number; sentiment: number; interactions: number }[];
  top_objections: { text: string; count: number; severity: "high" | "medium" | "low" }[];
}

